[package]
name = "registro_persone"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
regex = "1.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
